The task in this notebook is to read superstore sales data from a CSV, and then create TFRecords file from the data. This is a very simple approach and not suitable for large files.

In [21]:
import tensorflow as tf

import numpy as np
import IPython.display as display

In [22]:
# The following functions can be used to convert a value to a type compatible
# with tf.train.Example.

def _bytes_feature(value):
  """Returns a bytes_list from a string / byte."""
  if isinstance(value, type(tf.constant(0))):
    value = value.numpy() # BytesList won't unpack a string from an EagerTensor.
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def _float_feature(value):
  """Returns a float_list from a float / double."""
  return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

def _int64_feature(value):
  """Returns an int64_list from a bool / enum / int / uint."""
  return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

In [35]:
def serialize_example(feature0, feature1, feature2, feature3, feature4, 
                      feature5, feature6, feature7, feature8, feature9, 
                      feature10, feature11, feature12, feature13, feature14, 
                      feature15, feature16, feature17):
  """
  Creates a tf.train.Example message ready to be written to a file.
  """
  # Create a dictionary mapping the feature name to the tf.train.Example-compatible
  # data type.
  feature = {
      'feature0': _int64_feature(int(feature0)),
      'feature1': _bytes_feature(str.encode(feature1)),
      'feature2': _bytes_feature(str.encode(feature2)),
      'feature3': _bytes_feature(str.encode(feature3)),
      'feature4': _bytes_feature(str.encode(feature4)),
      'feature5': _bytes_feature(str.encode(feature5)),
      'feature6': _bytes_feature(str.encode(feature6)),
      'feature7': _bytes_feature(str.encode(feature7)),
      'feature8': _bytes_feature(str.encode(feature8)),
      'feature9': _bytes_feature(str.encode(feature9)),
      'feature10': _bytes_feature(str.encode(feature10)),
      'feature11': _bytes_feature(str.encode(feature11)),
      'feature12': _bytes_feature(str.encode(feature12)),
      'feature13': _bytes_feature(str.encode(feature13)),
      'feature14': _bytes_feature(str.encode(feature14)),
      'feature15': _bytes_feature(str.encode(feature15)),
      'feature16': _bytes_feature(str.encode(feature16)),
      'feature17': _float_feature(float(feature17))
  }

  # Create a Features message using tf.train.Example.

  example_proto = tf.train.Example(features=tf.train.Features(feature=feature))
  return example_proto.SerializeToString()

In [36]:
filename = 'test.tfrecord'

# Reading the data from a CSV file and Writing to TFRecords

In [40]:
import csv
headings = []
rows = []
with open('train.csv', mode ='r') as file:
  csvFileReader = csv.reader(file)
  headings = next(csvFileReader)
  # displaying the contents of the CSV file
  with tf.io.TFRecordWriter(filename, options = tf.io.TFRecordOptions(compression_type="GZIP")) as writer:
    for lines in csvFileReader:
      example = serialize_example(lines[0],lines[1],lines[2],lines[3],lines[4],
                                  lines[5],lines[6],lines[7],lines[8],lines[9],
                                  lines[10],lines[11],lines[12],lines[13],lines[14],
                                  lines[15],lines[16],lines[17])
      writer.write(example)

In [41]:
!du -sh {filename}

996K	test.tfrecord


In [42]:
!du -sh train.csv

2.1M	train.csv


# Read the data

In [45]:
filenames = [filename]
raw_dataset = tf.data.TFRecordDataset(filenames, compression_type="GZIP")
raw_dataset

<TFRecordDatasetV2 shapes: (), types: tf.string>

In [46]:
for raw_record in raw_dataset.take(10):
  print(repr(raw_record))

<tf.Tensor: shape=(), dtype=string, numpy=b'\n\x84\x04\n\x19\n\x08feature9\x12\r\n\x0b\n\tHenderson\n \n\tfeature13\x12\x13\n\x11\n\x0fFUR-BO-10001798\n\x1a\n\x08feature2\x12\x0e\n\x0c\n\n08/11/2017\n\x15\n\tfeature17\x12\x08\x12\x06\n\x04\xe1\xfa\x82C\n\x1a\n\x08feature3\x12\x0e\n\x0c\n\n11/11/2017\n\x11\n\x08feature0\x12\x05\x1a\x03\n\x01\x01\n\x1b\n\x08feature6\x12\x0f\n\r\n\x0bClaire Gute\n\x18\n\x08feature7\x12\x0c\n\n\n\x08Consumer\n\x16\n\tfeature12\x12\t\n\x07\n\x05South\n\x1a\n\tfeature15\x12\r\n\x0b\n\tBookcases\n\x19\n\tfeature10\x12\x0c\n\n\n\x08Kentucky\n\x16\n\tfeature11\x12\t\n\x07\n\x0542420\n2\n\tfeature16\x12%\n#\n!Bush Somerset Collection Bookcase\n\x1a\n\tfeature14\x12\r\n\x0b\n\tFurniture\n\x18\n\x08feature5\x12\x0c\n\n\n\x08CG-12520\n\x1d\n\x08feature8\x12\x11\n\x0f\n\rUnited States\n\x1c\n\x08feature4\x12\x10\n\x0e\n\x0cSecond Class\n\x1e\n\x08feature1\x12\x12\n\x10\n\x0eCA-2017-152156'>
<tf.Tensor: shape=(), dtype=string, numpy=b'\n\x9b\x04\n\x11\n\x08feature0\x

In [48]:
# Create a description of the features.
feature_description = {
    'feature0': tf.io.FixedLenFeature([], tf.int64, default_value=0),
    'feature1': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature2': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature3': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature4': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature5': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature6': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature7': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature8': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature9': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature10': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature11': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature12': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature13': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature14': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature15': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature16': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature17': tf.io.FixedLenFeature([], tf.float32, default_value=0.0),
}

def _parse_function(example_proto):
  # Parse the input `tf.train.Example` proto using the dictionary above.
  return tf.io.parse_single_example(example_proto, feature_description)

In [49]:
parsed_dataset = raw_dataset.map(_parse_function)
parsed_dataset

<MapDataset shapes: {feature0: (), feature1: (), feature10: (), feature11: (), feature12: (), feature13: (), feature14: (), feature15: (), feature16: (), feature17: (), feature2: (), feature3: (), feature4: (), feature5: (), feature6: (), feature7: (), feature8: (), feature9: ()}, types: {feature0: tf.int64, feature1: tf.string, feature10: tf.string, feature11: tf.string, feature12: tf.string, feature13: tf.string, feature14: tf.string, feature15: tf.string, feature16: tf.string, feature17: tf.float32, feature2: tf.string, feature3: tf.string, feature4: tf.string, feature5: tf.string, feature6: tf.string, feature7: tf.string, feature8: tf.string, feature9: tf.string}>

In [50]:
for parsed_record in parsed_dataset.take(10):
  print(repr(parsed_record))

{'feature0': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'feature1': <tf.Tensor: shape=(), dtype=string, numpy=b'CA-2017-152156'>, 'feature10': <tf.Tensor: shape=(), dtype=string, numpy=b'Kentucky'>, 'feature11': <tf.Tensor: shape=(), dtype=string, numpy=b'42420'>, 'feature12': <tf.Tensor: shape=(), dtype=string, numpy=b'South'>, 'feature13': <tf.Tensor: shape=(), dtype=string, numpy=b'FUR-BO-10001798'>, 'feature14': <tf.Tensor: shape=(), dtype=string, numpy=b'Furniture'>, 'feature15': <tf.Tensor: shape=(), dtype=string, numpy=b'Bookcases'>, 'feature16': <tf.Tensor: shape=(), dtype=string, numpy=b'Bush Somerset Collection Bookcase'>, 'feature17': <tf.Tensor: shape=(), dtype=float32, numpy=261.96>, 'feature2': <tf.Tensor: shape=(), dtype=string, numpy=b'08/11/2017'>, 'feature3': <tf.Tensor: shape=(), dtype=string, numpy=b'11/11/2017'>, 'feature4': <tf.Tensor: shape=(), dtype=string, numpy=b'Second Class'>, 'feature5': <tf.Tensor: shape=(), dtype=string, numpy=b'CG-12520'>, 'feature6': 

# Method 2

In [93]:
import pandas as pd
data = pd.read_csv('train.csv')

In [94]:
data.head()

Row ID  ...     Sales
0       1  ...  261.9600
1       2  ...  731.9400
2       3  ...   14.6200
3       4  ...  957.5775
4       5  ...   22.3680

[5 rows x 18 columns]

In [95]:
features_dataset = tf.data.Dataset.from_tensor_slices((data.iloc[:,0], data.iloc[:,1], data.iloc[:,2], data.iloc[:,3],
                                                       data.iloc[:,4], data.iloc[:,5], data.iloc[:,6], data.iloc[:,7],
                                                       data.iloc[:,8], data.iloc[:,9], data.iloc[:,10], data.iloc[:,11],
                                                       data.iloc[:,12], data.iloc[:,13], data.iloc[:,14], data.iloc[:,15],
                                                       data.iloc[:,16], data.iloc[:,17]))
features_dataset

<TensorSliceDataset shapes: ((), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), ()), types: (tf.int64, tf.string, tf.string, tf.string, tf.string, tf.string, tf.string, tf.string, tf.string, tf.string, tf.string, tf.float64, tf.string, tf.string, tf.string, tf.string, tf.string, tf.float64)>

In [96]:
def serialize_example(feature0, feature1, feature2, feature3, feature4, 
                      feature5, feature6, feature7, feature8, feature9, 
                      feature10, feature11, feature12, feature13, feature14, 
                      feature15, feature16, feature17):
  """
  Creates a tf.train.Example message ready to be written to a file.
  """
  # Create a dictionary mapping the feature name to the tf.train.Example-compatible
  # data type.
  feature = {
      'feature0': _int64_feature(feature0),
      'feature1': _bytes_feature(feature1),
      'feature2': _bytes_feature(feature2),
      'feature3': _bytes_feature(feature3),
      'feature4': _bytes_feature(feature4),
      'feature5': _bytes_feature(feature5),
      'feature6': _bytes_feature(feature6),
      'feature7': _bytes_feature(feature7),
      'feature8': _bytes_feature(feature8),
      'feature9': _bytes_feature(feature9),
      'feature10': _bytes_feature(feature10),
      'feature11': _float_feature(feature11),
      'feature12': _bytes_feature(feature12),
      'feature13': _bytes_feature(feature13),
      'feature14': _bytes_feature(feature14),
      'feature15': _bytes_feature(feature15),
      'feature16': _bytes_feature(feature16),
      'feature17': _float_feature(feature17)
  }

  # Create a Features message using tf.train.Example.

  example_proto = tf.train.Example(features=tf.train.Features(feature=feature))
  return example_proto.SerializeToString()

In [97]:
def tf_serialize_example(f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17):
  tf_string = tf.py_function(
    serialize_example,
    (f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17),  # Pass these args to the above function.
    tf.string)      # The return type is `tf.string`.
  return tf.reshape(tf_string, ()) # The result is a scalar.

In [98]:
serialized_features_dataset = features_dataset.map(tf_serialize_example)
serialized_features_dataset

<MapDataset shapes: (), types: tf.string>

In [99]:
def generator():
  for features in features_dataset:
    yield serialize_example(*features)

In [100]:
serialized_features_dataset = tf.data.Dataset.from_generator(
    generator, output_types=tf.string, output_shapes=())

In [101]:
serialized_features_dataset

<FlatMapDataset shapes: (), types: tf.string>

In [102]:
filename = 'test1.tfrecord'
writer = tf.data.experimental.TFRecordWriter(filename)
writer.write(serialized_features_dataset)

In [103]:
filenames = [filename]
raw_dataset = tf.data.TFRecordDataset(filenames)
raw_dataset

<TFRecordDatasetV2 shapes: (), types: tf.string>

In [104]:
for raw_record in raw_dataset.take(10):
  print(repr(raw_record))

<tf.Tensor: shape=(), dtype=string, numpy=b'\n\x83\x04\n\x18\n\x08feature5\x12\x0c\n\n\n\x08CG-12520\n2\n\tfeature16\x12%\n#\n!Bush Somerset Collection Bookcase\n\x18\n\x08feature7\x12\x0c\n\n\n\x08Consumer\n\x1e\n\x08feature1\x12\x12\n\x10\n\x0eCA-2017-152156\n\x1a\n\tfeature14\x12\r\n\x0b\n\tFurniture\n\x1a\n\x08feature2\x12\x0e\n\x0c\n\n08/11/2017\n\x1a\n\tfeature15\x12\r\n\x0b\n\tBookcases\n\x15\n\tfeature11\x12\x08\x12\x06\n\x04\x00\xb4%G\n\x1b\n\x08feature6\x12\x0f\n\r\n\x0bClaire Gute\n\x11\n\x08feature0\x12\x05\x1a\x03\n\x01\x01\n\x1a\n\x08feature3\x12\x0e\n\x0c\n\n11/11/2017\n\x1c\n\x08feature4\x12\x10\n\x0e\n\x0cSecond Class\n \n\tfeature13\x12\x13\n\x11\n\x0fFUR-BO-10001798\n\x16\n\tfeature12\x12\t\n\x07\n\x05South\n\x19\n\tfeature10\x12\x0c\n\n\n\x08Kentucky\n\x15\n\tfeature17\x12\x08\x12\x06\n\x04\xe1\xfa\x82C\n\x1d\n\x08feature8\x12\x11\n\x0f\n\rUnited States\n\x19\n\x08feature9\x12\r\n\x0b\n\tHenderson'>
<tf.Tensor: shape=(), dtype=string, numpy=b'\n\x9a\x04\n\x1a\n\x08f

In [105]:
# Create a description of the features.
feature_description = {
    'feature0': tf.io.FixedLenFeature([], tf.int64, default_value=0),
    'feature1': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature2': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature3': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature4': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature5': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature6': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature7': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature8': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature9': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature10': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature11': tf.io.FixedLenFeature([], tf.float32, default_value=0.0),
    'feature12': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature13': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature14': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature15': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature16': tf.io.FixedLenFeature([], tf.string, default_value=''),
    'feature17': tf.io.FixedLenFeature([], tf.float32, default_value=0.0),
}

def _parse_function(example_proto):
  # Parse the input `tf.train.Example` proto using the dictionary above.
  return tf.io.parse_single_example(example_proto, feature_description)

In [106]:
parsed_dataset = raw_dataset.map(_parse_function)
parsed_dataset

<MapDataset shapes: {feature0: (), feature1: (), feature10: (), feature11: (), feature12: (), feature13: (), feature14: (), feature15: (), feature16: (), feature17: (), feature2: (), feature3: (), feature4: (), feature5: (), feature6: (), feature7: (), feature8: (), feature9: ()}, types: {feature0: tf.int64, feature1: tf.string, feature10: tf.string, feature11: tf.float32, feature12: tf.string, feature13: tf.string, feature14: tf.string, feature15: tf.string, feature16: tf.string, feature17: tf.float32, feature2: tf.string, feature3: tf.string, feature4: tf.string, feature5: tf.string, feature6: tf.string, feature7: tf.string, feature8: tf.string, feature9: tf.string}>

In [107]:
for parsed_record in parsed_dataset.take(10):
  print(repr(parsed_record))

{'feature0': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'feature1': <tf.Tensor: shape=(), dtype=string, numpy=b'CA-2017-152156'>, 'feature10': <tf.Tensor: shape=(), dtype=string, numpy=b'Kentucky'>, 'feature11': <tf.Tensor: shape=(), dtype=float32, numpy=42420.0>, 'feature12': <tf.Tensor: shape=(), dtype=string, numpy=b'South'>, 'feature13': <tf.Tensor: shape=(), dtype=string, numpy=b'FUR-BO-10001798'>, 'feature14': <tf.Tensor: shape=(), dtype=string, numpy=b'Furniture'>, 'feature15': <tf.Tensor: shape=(), dtype=string, numpy=b'Bookcases'>, 'feature16': <tf.Tensor: shape=(), dtype=string, numpy=b'Bush Somerset Collection Bookcase'>, 'feature17': <tf.Tensor: shape=(), dtype=float32, numpy=261.96>, 'feature2': <tf.Tensor: shape=(), dtype=string, numpy=b'08/11/2017'>, 'feature3': <tf.Tensor: shape=(), dtype=string, numpy=b'11/11/2017'>, 'feature4': <tf.Tensor: shape=(), dtype=string, numpy=b'Second Class'>, 'feature5': <tf.Tensor: shape=(), dtype=string, numpy=b'CG-12520'>, 'feature6': 